### ISSUE TITLE
Exception Value: int() argument must be a string, a bytes-like object or a number, not 'ObjectId'

### ISSUE THREAD

**Issue by iemektar** [MongoEngine/django-mongoengine#105]
When i try to login to admin panel i have this issue
please help me

Environment:

```
Request Method: GET
Request URL: http://localhost:8000/admin/

Django Version: 1.11.6
Python Version: 3.6.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_mongoengine',
 'django_mongoengine.mongo_auth',
 'django_mongoengine.mongo_admin',
 'bootstrap3']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\contrib\admin\templates\admin\base.html, error at line 44
   int() argument must be a string, a bytes-like object or a number, not 'ObjectId'   34 :                 {% if site_url %}
   35 :                     <a href="{{ site_url }}">{% trans 'View site' %}</a> /
   36 :                 {% endif %}
   37 :                 {% if user.is_active and user.is_staff %}
   38 :                     {% url 'django-admindocs-docroot' as docsroot %}
   39 :                     {% if docsroot %}
   40 :                         <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
   41 :                     {% endif %}
   42 :                 {% endif %}
   43 :                 {% if user.has_usable_password %}
   44 :                 <a href="{% url 'admin: password_change' %}">{% trans 'Change password' % }</a> /
   45 :                 {% endif %}
   46 :                 <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
   47 :             {% endblock %}
   48 :         </div>
   49 :         {% endif %}
   50 :         {% endblock %}
   51 :         {% block nav-global %}{% endblock %}
   52 :     </div>
   53 :     <!-- END Header -->
   54 :     {% block breadcrumbs %}


Traceback:

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\core\handlers\exception.py" in inner
  41.             response = get_response(request)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\core\handlers\base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\core\handlers\base.py" in _get_response
  215.                 response = response.render()

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\response.py" in render
  107.             self.content = self.rendered_content

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\response.py" in rendered_content
  84.         content = template.render(context, self._request)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\backends\django.py" in render
  66.             return self.template.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render
  207.                     return self._render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in _render
  199.         return self.nodelist.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render
  990.                 bit = node.render_annotated(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render_annotated
  957.             return self.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in _render
  199.         return self.nodelist.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render
  990.                 bit = node.render_annotated(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render_annotated
  957.             return self.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in _render
  199.         return self.nodelist.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render
  990.                 bit = node.render_annotated(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render_annotated
  957.             return self.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\loader_tags.py" in render
  72.                 result = block.nodelist.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render
  990.                 bit = node.render_annotated(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\template\base.py" in render_annotated
  957.             return self.render(context)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\contrib\admin\templatetags\log.py" in render
  21.             entries = LogEntry.objects.filter(user__pk=user_id)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\query.py" in filter
  784.         return self._filter_or_exclude(False, *args, **kwargs)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\query.py" in _filter_or_exclude
  802.             clone.query.add_q(Q(*args, **kwargs))

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\sql\query.py" in add_q
  1250.         clause, _ = self._add_q(q_object, self.used_aliases)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\sql\query.py" in _add_q
  1276.                     allow_joins=allow_joins, split_subq=split_subq,

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\sql\query.py" in build_filter
  1210.             condition = self.build_lookup(lookups, col, value)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\sql\query.py" in build_lookup
  1104.                 return final_lookup(lhs, rhs)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\lookups.py" in __init__
  24.         self.rhs = self.get_prep_lookup()

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\lookups.py" in get_prep_lookup
  74.             return self.lhs.output_field.get_prep_value(self.rhs)

File "C:\Users\IBRAHIM.DESKTOP-SCJPS5O\Desktop\GPSTakip\env\lib\site-packages\django\db\models\fields\__init__.py" in get_prep_value
  966.         return int(value)

Exception Type: TypeError at /admin/
Exception Value: int() argument must be a string, a bytes-like object or a number, not 'ObjectId'
```
_______________________________

Data of super user:
```
{ "_id" : ObjectId("59e8e8542c3bdf53002dda86"), "_cls" : "User", "username" : "iemektar", "email" : "example@example.com", "password" : "pbkdf2_sha256$36000$6mXGnAw3SSps$l5tNkXkwu4A3P9jxCjg6J9t44TLY+b5fZRdV8TRA9g=", "is_staff" : true, "is_active" : true, "is_superuser" : true, "last_login" : ISODate("2017-10-20T08:58:16.829Z"), "date_joined" : ISODate("2017-10-19T18:00:52.531Z"), "user_permissions" : [ ] }
```

**Comment by last-partizan** [comment]
Try to reproduce error using example app, and then find differences in your configuration.

**Comment by iemektar** [comment]
I added this lines in main urls.py and it worked ;

from django_mongoengine import mongo_admin
urlpatterns+= [url(r'^mongoadmin/', mongo_admin.site.urls),]

**Comment by scollet1** [comment]
;-;

I am trying to save a object with foreign keys and I'm getting the same error

traceback:

```
Traceback (most recent call last):
  File "transDB_script.py", line 198, in <module>
    thisGame.save()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 823, in _save_table
    forced_update)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 852, in _do_update
    filtered = base_qs.filter(pk=pk_val)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 947, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'ObjectId'
[1]+  Done                    clear
```

model to save:

```
class Game(models.Model):
    date = models.DateField()
    daysBetweenGames = models.IntegerField()
    gameCount = models.IntegerField()
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
```

**Comment by last-partizan** [comment]
Are you trying to save django model using mongodb somehow?

(btw, take a look at https://nesdis.github.io/djongo/, maybe it's better option now)

**Comment by nikhilbhingarkar** [comment]
I got the following  error while creating Models

TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
