### ISSUE TITLE
AttributeError in django_mongoengine.mongo_auth.models when do Permission.objects.all()

### ISSUE THREAD

**Issue by mrbrazzi** [MongoEngine/django-mongoengine#119]
I'm trying to create a command to add groups. I'm using MongoDB to storage data. 

When I try to do any of this:

    from django_mongoengine.mongo_auth.models import ContentType, Group, Permission
    
    permission = Permission.objects.get(name=permission_name)
or

    permissions = Permission.objects.all()
or

    permission_total = Permissions.object.count()

I got this error:

    Traceback (most recent call last):
      [...]
      File "./manage.py", line 14, in <module>
        execute_from_command_line(sys.argv)
      File "virtualenv\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "virtualenv\lib\site-packages\django\core\management\__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "virtualenv\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
      File "virtualenv\lib\site-packages\django\core\management\base.py", line 330, in execute
        output = self.handle(*args, **options)
      File "app\management\commands\add_groups_tomongo.py", line 119, in handle
        permissions = Permission.objects.all()
      File "virtualenv\lib\site-packages\django\db\models\query.py", line 250, in __iter__
        self._fetch_all()
      File "virtualenv\lib\site-packages\django\db\models\query.py", line 1118, in _fetch_all
        self._result_cache = list(self._iterable_class(self))
      File "virtualenv\lib\site-packages\django\db\models\query.py", line 53, in __iter__
        results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
      File "virtualenv\lib\site-packages\django\db\models\sql\compiler.py", line 871, in execute_sql
        sql, params = self.as_sql()
      File "virtualenv\lib\site-packages\django\db\models\sql\compiler.py", line 423, in as_sql
        extra_select, order_by, group_by = self.pre_sql_setup()
      File "virtualenv\lib\site-packages\django\db\models\sql\compiler.py", line 46, in pre_sql_setup
        self.setup_query()
      File "virtualenv\lib\site-packages\django\db\models\sql\compiler.py", line 36, in setup_query
        self.query.get_initial_alias()
      File "virtualenv\lib\site-packages\django\db\models\sql\query.py", line 892, in get_initial_alias
        alias = self.join(BaseTable(self.get_meta().db_table, None))
      File "virtualenv\lib\site-packages\django\db\models\sql\query.py", line 264, in get_meta
        return self.model._meta
    AttributeError: 'NoneType' object has no attribute '_meta'

Thanks in advance.

**Comment by last-partizan** [comment]
Hello @mrbrazzi 

I fixed this issue.

**Comment by mrbrazzi** [comment]
Thanks @last-partizan, I test and now works as expected.
