### ISSUE TITLE
run example failed

### ISSUE THREAD

**Issue by mela93** [MongoEngine/django-mongoengine#125]
```
$ ./env/bin/python example/tumblelog/manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x110bf5488>
Traceback (most recent call last):
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/urls/conf.py", line 17, in include
    urlconf_module, app_name = arg
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/core/management/cotsands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/example/tumblelog/tumblelog/urls.py", line 25, in <module>
    url(r'^admin/', include(mongo_admin.site.urls)),
  File "/Users/ts/Desktop/Project/PythonExample/django-mongoengine-master/env/lib/python3.7/site-packages/django/urls/conf.py", line 27, in include
    'provide the namespace argument to include() instead.' % len(arg)
django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
```

**Comment by last-partizan** [comment]
Fixed this.
