### ISSUE TITLE
error installing 0.3.2

### ISSUE THREAD

**Issue by dblado** [MongoEngine/django-mongoengine#130]
I get the following error when attempting to install 0.3.2:

$ pip install django-mongoengine==0.3.2
Collecting django-mongoengine==0.3.2
  Using cached https://files.pythonhosted.org/packages/11/4a/a6c97301c6cd3a4acff94d823c94525e257a8545e293816a7b55b164bb4d/django-mongoengine-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b4/qg1v4zs94lx66r0kr7cxsl5c0000gn/T/pip-install-NYeo48/django-mongoengine/setup.py", line 32, in <module>
        REQUIRES = [i.strip() for i in open("requirements.txt").readlines()]
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b4/qg1v4zs94lx66r0kr7cxsl5c0000gn/T/pip-install-NYeo48/django-mongoengine/

Works with pip install -e git://github.com/MongoEngine/django-mongoengine@7fdf0c3d4e5555e37ab9c96fb415f39ab6f56384#egg=django-mongoengine

**Comment by dblado** [comment]
Pypi has 0.3.3 which does work, must be something wrong w/ the 0.3.2 package
