### ISSUE TITLE
Error updating objects with FileFields

### ISSUE THREAD

**Issue by fmoro** [MongoEngine/django-mongoengine#30]
BaseDocumentForm perform an update instead of save the hole object witch is great, but if the form contains a FileField (or ImageField) it won't be converted to a GridFS file, so mongoengine raises an AttributeError since object is InMemoryUploadedFile.

This bug can be confirmed with the example application editing an image post.

 ```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/darkstar/django-mongoengine/django_mongoengine/views/edit.py", line 214, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/home/darkstar/django-mongoengine/django_mongoengine/views/edit.py", line 62, in form_valid
    self.object = form.save()
  File "/home/darkstar/django-mongoengine/django_mongoengine/forms/documents.py", line 424, in save
    self.instance.update(**update)
  File "/usr/lib64/python2.7/site-packages/mongoengine/document.py", line 465, in update
    return self._qs.filter(**self._object_key).update_one(**kwargs)
  File "/usr/lib64/python2.7/site-packages/mongoengine/queryset/base.py", line 487, in update_one
    upsert=upsert, multi=False, write_concern=write_concern, **update)
  File "/usr/lib64/python2.7/site-packages/mongoengine/queryset/base.py", line 448, in update
    update = transform.update(queryset._document, **update)
  File "/usr/lib64/python2.7/site-packages/mongoengine/queryset/transform.py", line 249, in update
    value = field.prepare_query_value(op, value)
  File "/usr/lib64/python2.7/site-packages/mongoengine/base/fields.py", line 160, in prepare_query_value
    self.validate(value)
  File "/usr/lib64/python2.7/site-packages/mongoengine/fields.py", line 1461, in validate
    if value.grid_id is not None:
AttributeError: 'InMemoryUploadedFile' object has no attribute 'grid_id'
```

An easy sollution for this issue can be replace save function on BaseDocumentForm. Here you have a patch:

```
diff -rupN django-mongoengine.orig/django_mongoengine/forms/documents.py django-mongoengine/django_mongoengine/forms/documents.py
--- django-mongoengine.orig/django_mongoengine/forms/documents.py	2015-09-23 16:28:34.090070123 +0200
+++ django-mongoengine/django_mongoengine/forms/documents.py	2015-09-23 16:29:46.080070311 +0200
@@ -391,37 +391,15 @@ class BaseDocumentForm(BaseForm):
             raise ValueError("The %s could not be %s because the data didn't"
                              " validate." % (self.instance.__class__.__name__, fail_message))
 
-        if self.instance._created:
-            self.instance = construct_instance(self, self.instance, self.fields, self._meta.exclude)
+        self.instance = construct_instance(self, self.instance, self.fields, self._meta.exclude)
 
-            # Validate uniqueness if needed.
-            if self._validate_unique:
-                self.validate_unique()
-
-            if commit:
-                self.instance.save()
-        else:
-            update = {}
-            for name, data in self.cleaned_data.iteritems():
+        # Validate uniqueness if needed.
+        if self._validate_unique:
+            self.validate_unique()
 
-                try:
-                    if isinstance(data, datetime.datetime):
-                        data = data.replace(tzinfo=None)
-                    if getattr(self.instance, name) != data:
-                        update['set__' + name] = data
-                        setattr(self.instance, name, data)
-                except AttributeError:
-                    raise Exception('Model %s has not attr %s but form %s has' \
-                                    % (type(self.instance),
-                                      name,
-                                      type(self)))
-
-            # Validate uniqueness if needed.
-            if self._validate_unique:
-                self.validate_unique()
+        if commit:
+            self.instance.save()
 
-            if commit and update:
-                self.instance.update(**update)
         return self.instance
     save.alters_data = True
```

**Comment by last-partizan** [comment]
Thanks for reporting.

I will investigate this issue.

**Comment by last-partizan** [comment]
Fixed issue with your patch, thanks.
