### ISSUE TITLE
Does it work with python 3?

### ISSUE THREAD

**Issue by Snpefk** [MongoEngine/django-mongoengine#34]

**Comment by last-partizan** [comment]
No, it does not work with python3.

Right now i don't have plans to add it, but accept any pull-requests if you can add it.

**Comment by Alex131089** [comment]
It is a syntax problem or does things needs to be redefined ?
In the head revision, I fixed 4 python3 incompatibilities, so it build&install without error, but it doesn't start.
Here's the error : 
```
(pyenv)17:10 emma@dev ~/app-django % python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f633c34d8c8>
Traceback (most recent call last):
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/srv/emma/pyenv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/srv/emma/pyenv/lib/python3.4/site-packages/django_mongoengine-0.1.1-py3.4.egg/django_mongoengine/mongo_admin/__init__.py", line 1, in <module>
    from django_mongoengine.mongo_admin.options import *
  File "/srv/emma/pyenv/lib/python3.4/site-packages/django_mongoengine-0.1.1-py3.4.egg/django_mongoengine/mongo_admin/options.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/srv/emma/pyenv/lib/python3.4/site-packages/Django-1.9.1-py3.4.egg/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
Should I assume it is python3 incompatibility, regarding the error ?

**Comment by last-partizan** [comment]
Today i was fixing many errors for django 1.9; just commited everything; update your repo and try again
