### ISSUE TITLE
Django mongoengine Connection Support

### ISSUE THREAD

**Issue by manishgupta24** [MongoEngine/django-mongoengine#46]
I am trying to use django-mongoengine with my project but I am facing some connectivity issues regarding auth and sessions. I am using django v1.9.2. I only want to use sessions and auth.

This I added in my settings:
```
MONGODB_DATABASES = {
    "default": {
        "name": 'picknbox',
        "host": '127.0.0.1',
        # "password": database_password,
        # "username": database_user,
         "tz_aware": True, # if you using timezones in django (USE_TZ = True)
    },
}

DATABASES = {
    'default': {'ENGINE': 'django.db.backends.dummy'}
}

INSTALLED_APPS += ["django_mongoengine"]
SESSION_ENGINE = 'django_mongoengine.sessions'
SESSION_SERIALIZER = 'django_mongoengine.sessions.BSONSerializer'
```

Where can I see the `auth_user` and `django_sessions` collections? I cant see them in my mongodb instance?
Also When I run `python manage.py migrate`, it throws an error regarding Database Improperly Configured.

Also if you can provide some more instructions that would be great.
Thanks

**Comment by last-partizan** [comment]
Take a look at example/tumblelog/settings.py
That project is configured to use mongo sessions and auth.

manage.py migrate is supposed to throw that exception, becouse you don't setup any databases besides mongo and mongo doesn't use migrations

**Comment by manishgupta24** [comment]
I edited my settings.py file according to tumblelog example. But It is still throwing error:

`TypeError: __init__() got an unexpected keyword argument 'auto_created'`
I have attached settings.py file. and error log is:

[http://tempsend.com/3457C79CD2](url)

```
Unhandled exception in thread started by <function wrapper at 0x7f69f92ea398>
Traceback (most recent call last):
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django_mongoengine-0.2.1-py2.7.egg/django_mongoengine/mongo_auth/models.py", line 42, in <module>
    class ContentType(document.Document):
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django_mongoengine-0.2.1-py2.7.egg/django_mongoengine/mongo_auth/models.py", line 43, in ContentType
    name = fields.StringField(max_length=100)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/django_mongoengine-0.2.1-py2.7.egg/django_mongoengine/fields/djangoflavor.py", line 27, in __init__
    super(DjangoField, self).__init__(*args, **kwargs)
  File "/home/manish/Desktop/admin_picknbox/local/lib/python2.7/site-packages/mongoengine/fields.py", line 63, in __init__
    super(StringField, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'auto_created'
``

**Comment by last-partizan** [comment]
Loosks like a bug; post your mongoengine version and i will look into it later today.

**Comment by manishgupta24** [comment]
Yeah it was mongoengine issue.. I upgraded it and it worked like a charm. Thanks a lot.
