### ISSUE TITLE
Create admin login credentials

### ISSUE THREAD

**Issue by npatel33** [MongoEngine/django-mongoengine#47]
Hello, 

I have downloaded your example and it works well with mongoDB on my machine. But now i want to create admin login credential. is there a way to do it or is it just broken for now?

**Comment by last-partizan** [comment]
Admin user can be created using `manage.py createsuperuser`

**Comment by npatel33** [comment]
I tried creating but i am getting an error and can't login to admin panel:

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 52, in execute
    return super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/management/commands/createsuperuser.py", line 173, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 165, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 147, in _create_user
    user.set_password(password)
  File "/home/prasad/Desktop/django-mongoengine/django_mongoengine/mongo_auth/models.py", line 228, in set_password
    self.save()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.10.6-py2.7.egg/mongoengine/document.py", line 304, in save
  File "/usr/local/lib/python2.7/dist-packages/mongoengine-0.10.6-py2.7.egg/mongoengine/base/document.py", line 413, in validate
mongoengine.errors.ValidationError: ValidationError (User:None) (Field is required: ['first_name', 'last_name'] Field is required and cannot be empty: ['user_permissions'])`

**Comment by last-partizan** [comment]
Update to latest version from github, just fixed this

**Comment by npatel33** [comment]
Hey thanks a lot. It is working now. :+1:
