### ISSUE TITLE
python manage.py createsuperuser not working

### ISSUE THREAD

**Issue by ftahery** [MongoEngine/django-mongoengine#94]
```
Username: mongouser
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 63, in execute
    return super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 121, in handle
    self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 48, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python2.7/site-packages/django_mongoengine-0.2.1-py2.7.egg/django_mongoengine/mongo_auth/managers.py", line 89, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django_mongoengine-0.2.1-py2.7.egg/django_mongoengine/mongo_auth/managers.py", line 99, in get_queryset
    return get_user_document().objects
  File "/usr/local/lib/python2.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 173, in _get_collection
    db = cls._get_db()
  File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 166, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "/usr/local/lib/python2.7/site-packages/mongoengine/connection.py", line 225, in get_db
    conn = get_connection(alias)
  File "/usr/local/lib/python2.7/site-packages/mongoengine/connection.py", line 146, in get_connection
    raise MongoEngineConnectionError(msg)
mongoengine.connection.MongoEngineConnectionError: You have not defined a default connection
```
**How do I resolve this?**

**Comment by last-partizan** [comment]
> mongoengine.connection.MongoEngineConnectionError: You have not defined a default connection

did you set up your database in MONGODB_DATABASES?

**Comment by ftahery** [comment]
Yes I have set up my database in MONGODB_DATABASES

**Comment by last-partizan** [comment]
Let's update master branch and try `createmongodbsuperuser` (it must work, i just fixed it)

**Comment by ftahery** [comment]
I have tried this as well and it doesn't work. It says 'createmongodbsuperuser' is and unknown command

**Comment by last-partizan** [comment]
Looks like you forgot to add 'django_mongoengine.mongo_admin' to installed apps

**Comment by ftahery** [comment]
Thank you. That works.
Just facing another issue regarding authentication failure.

**Comment by last-partizan** [comment]
What issue?

**Comment by ftahery** [comment]
It says that the authentication fails as soon as I enter the username
`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django_mongoengine/mongo_admin/management/commands/createmongodbsuperuser.py", line 98, in handle
    MongoUser.objects.get(username=username)
  File "/usr/local/lib/python2.7/site-packages/django_mongoengine/mongo_auth/managers.py", line 89, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django_mongoengine/mongo_auth/managers.py", line 99, in get_queryset
    return get_user_document().objects
  File "/usr/local/lib/python2.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 173, in _get_collection
    db = cls._get_db()
  File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 166, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "/usr/local/lib/python2.7/site-packages/mongoengine/connection.py", line 234, in get_db
    db.authenticate(conn_settings['username'], conn_settings['password'], **auth_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymongo/database.py", line 1048, in authenticate
    connect=True)
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 505, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 523, in authenticate
    auth.authenticate(credentials, self)
  File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 470, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 450, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 201, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/usr/local/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
`

**Comment by last-partizan** [comment]
> pymongo.errors.OperationFailure: Authentication failed.

this is about your connection to mongodb
